FROM debian:bookworm-slim AS builder
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev cmake ca-certificates ninja-build g++ git && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/src
COPY . .
RUN cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja && cmake --build build

FROM debian:bookworm-slim
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/isolate.asc] http://www.ucw.cz/isolate/debian/ bookworm-isolate main" > /etc/apt/sources.list.d/isolate.list
ADD https://www.ucw.cz/isolate/debian/signing-key.asc /etc/apt/keyrings/isolate.asc
RUN chmod 644 /etc/apt/keyrings/isolate.asc
RUN apt-get update && apt-get install -y --no-install-recommends isolate libpq-dev python3.11 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /opt/src/build/main /usr/local/bin/
CMD [ "/usr/local/bin/main" ]